### ISSUE TITLE
GNSS Auth: expose GNSS messaging sigs to ODC API

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/odc-api#11]
Private keys on M9N to validate signature and hw is authenticity.

**Comment by jayalberts** [comment]
solution from HB not good.
today auth message out of GPSD, flash keys work with John
Need to document process

**Comment by jayalberts** [comment]
keys flashed onto dev camera. get dev build on cam. Slow but steady progress.

**Comment by jayalberts** [comment]
Blocker was test device didn't have GNSS keys. No accurate documentation outside of hellbender. 

TN036 built before flashing keys. No UFL. No device ID EEProm.

**Comment by jayalberts** [comment]
can install 3rd party modules to unpack GNSS. Today will be sampling.

**Comment by BenDavidAaron** [comment]
Posting for others to gain context:
I have a script to sniff messages using `gpspipe -R`, so far I have not been able to sample any messages using `gpspipe` (which consumes them from `gpsd`) I'll be tweaking with the m9n configuration until I can get it to broadcast SEC-ECSIGN messages on the correct interface. So far I've tried UART1, sampling UART2 now.

**Comment by BenDavidAaron** [comment]
Got the proper configuration commands from Caleb at Hellbender. Looks like this is ready to be folded into the ODC-API. Will open a PR soon. 
Docs on setting up ECSIGN Messages:
https://www.notion.so/How-do-I-enable-message-signing-on-HDC-d2520866b30842a3aa8b1f09031f1380

**Comment by BenDavidAaron** [comment]
Have a PR ready for review (https://github.com/Hivemapper/odc-api/pull/8) that exposes binary GNSS messages to callers. 

This will also need some configuration changes to the M9N, I'm following up with Hellbender to figure out the best approach.

**Comment by jayalberts** [comment]
Ready for firmware, need verification

**Comment by BenDavidAaron** [comment]
Message contents verified, PR Merged 🚀

**Comment by BenDavidAaron** [comment]
I don't know what release process this requires (since it's part of firmware). 
@punov can you weigh in?

**Comment by jayalberts** [comment]
we already started testing on 0.11.11, so likely this included in next version for 0.11.12. Does this require any driving tests before it can be released widely?

**Comment by jayalberts** [comment]
This has been merged
