### ISSUE TITLE
Read SQLite data frameKm should be a km of data

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/odc-api#113]
logic should not be subsequent rules (e.g. GNSS 3 points)

include stopping condition for bad IMU

**Comment by jayalberts** [comment]
discovered issues chunking framekms and working on solution. Ability to finish today depends on data validation 3.6.

**Comment by jayalberts** [comment]
working on slight refactor for persistent behaviors in SQLite instead of folder system

**Comment by jayalberts** [comment]
Some topics to discuss with Evan related to motion model math -- send in slack. Create PR for Evan, sooner the better.

**Comment by punov** [comment]
In review: https://github.com/Hivemapper/odc-api/pull/117
Moving to testing tomorrow, including all the fixes needed

**Comment by jayalberts** [comment]
finished architectural skeleton and shared with Evan, focus today is on testing and discovering failure modes. Adding safety checks.
