### ISSUE TITLE
Method to call gyro & accelerometer calibration from odc-api

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/odc-api#127]
Requirements:
- Gyroscope calibrates successfully when device is powered on and not moving
- For Testing: Gyroscope test can be triggered in SSH using a command

**Comment by evanmoss** [comment]
- In the naive case, we can assume the vehicle isn't moving when the power first comes on and call the calibration for gyro on boot up.

- A better solution is to opportunistically detect no movement and periodically calibrate the IMU when it hasn't been calibrated yet (or hasn't been calibrated in _t_ minutes (30?).

**Comment by jayalberts** [comment]
Added ODC service to calibrate gyro and accel. Seems to be working, end of today should have PR.

**Comment by jayalberts** [comment]
required permissions, running into build issues.

**Comment by jayalberts** [comment]
was able to build new image, was able to test and it works. submitted PR.

**Comment by jayalberts** [comment]
PRs merged

**Comment by jayalberts** [comment]
Masaya has a test written for this

**Comment by jayalberts** [comment]
Released in HDC 3.8.1, still need to include for HDC-S release

**Comment by jayalberts** [comment]
released in 3.8.17 for HDC-S
