### ISSUE TITLE
Bee Dashcam: Accelerometer calibration

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/odc-api#184]
Investigate accelerometer calibration methods

Continuation of https://github.com/Hivemapper/odc-api/issues/135

**Comment by Masaya-RT** [comment]
Roger showed Mazar an algorithm example we can get started with. Mazar to investigate this lead

**Comment by mazar-farran** [comment]
Tried Roger's algorithm, not much improvement.
Not focusing on this yet, to focus on Magnet+other tasks

**Comment by mazar-farran** [comment]
No work currently being done, accelerometer readings seem good enough without extra calibration. Will return if the need arises
