### ISSUE TITLE
Add "metadata" for sensor telemetry JSONs

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/odc-api#200]
Sensor telemetry JSONs currently store all information in the individual entries, even if the information is the same across all entries (e.g. device ID).  We should factor these out instead of sending a simple array.

Current format:
```
[ {device_id:"foo", sensor:"gnss", "lat":100.0, ... }, {device_id:"foo", sensor:"imu", "acc_x":0.15, ... }, ... ]
```

Proposed format:
```
{
   metadata: {
      deviceId: "foo"
   },
   data: [ {sensor:"gnss", "lat":100.0, ... }, {sensor:"imu", "acc_x":0.15, ... }, ... ]
}
```

The server side will not change at all. data will be sent as simple arrays like before. The only difference is the HTTP body (?) will contain the metadata e.g. `req.body.deviceID`

Possible issues:

More parsing needed? No because we already need to parse the JSONs in the mobile app to combine them
Combining more complex? No, we can pretty trivially change the combine code to accomodate for this

**Comment by mazar-farran** [comment]
This is actually more complex than I thought. S3MultipartUploader() takes a file path so I can't arbitrarily change the format of the JSON.

We need to create separate files for metadata and sensordata

**Comment by Masaya-RT** [comment]
Idea: Single, flat array of all fields in SensTel
- This will factor out fields common to all entries

Has a draft PR, but found issues after. Revising more to fix

**Comment by Masaya-RT** [comment]
The PR is ready for Review. After approval, do E2E testing to make sure this is working.

**Comment by Masaya-RT** [comment]
Has been reviewed, rebased in app 7.5.

Wants to take look at old firmware compatibility

**Comment by Masaya-RT** [comment]
Merged to 7.5
Next step to give to CTP

Mazar's best approach rec: 
- Ensure no changes/incompatibility: Make sure all changes are deployed to CTP so that next FW doesn't cause issues

**Comment by Masaya-RT** [comment]
Waiting for CTP release, moved to ready cc @HariHive

**Comment by mazar-farran** [comment]
Done
