### ISSUE TITLE
ODC-API E2E Test -- Investigate using http endpoints for all tests.

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/odc-api#206]
Currently, the end-to-end test uses shell scripts that compare files produced by ODC-API to a reference.

It would be better if we make use of the HTTP endpoints (like `/metadata`) and use those for comparison instead.

This accomplishes two things
1. We would now also be covering the endpoint code, so we'd know if there was a regression there.
2. We can use more mature test frameworks.  Testing a backend server is a common scenario, so there are definitely good frameworks to cover this.

**Comment by Masaya-RT** [comment]
Using a webserver framework for testing instead of current
-> tried using supertests (in code base) but not currently working as expected. Deep dive to see what can be done.

**Comment by mazar-farran** [comment]
Won't do
