### ISSUE TITLE
Triage HDC memory leaks related to privacy processing

### ISSUE THREAD

**Issue by punov** [Hivemapper/odc-api#92]
- Happens after ~20min
- Investigate yappi logs
- Try valgrind for identifying memory issues
- Add loaded images and model stats/snapshots for ml stuff

**Comment by punov** [comment]
When looked closer to the memory usage, 
on every iteration over the folder, memory is getting filled with the imagery that is eventually getting cleared, but not before the next iteration.

Having an extra swap space helps to mitigate that, all the memory is eventually getting freed up, + some additional garbage collector executions

![Image](https://github.com/Hivemapper/odc-api/assets/3530859/ec1e7507-a0e5-4aa4-a96f-9813a2bbed62)

**Comment by jayalberts** [comment]
no new tickets to create, nothing to release.
